// <auto-generated />
using System;
using MediClinic.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediClinic.Migrations
{
    [DbContext(typeof(MediClinicDbContext))]
    [Migration("20260218105704_ConfirmDatabase")]
    partial class ConfirmDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediClinic.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime?>("AppointmentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Criticality")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RequiredSpecialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduleStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("AppointmentId")
                        .HasName("PK__Appointm__8ECDFCA22DB0FA67");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("MediClinic.Models.Chemist", b =>
                {
                    b.Property<int>("ChemistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChemistID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChemistId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ChemistName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ChemistStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Summary")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ChemistId")
                        .HasName("PK__Chemist__C0D5B7B4C293BF6D");

                    b.ToTable("Chemist", (string)null);
                });

            modelBuilder.Entity("MediClinic.Models.Drug", b =>
                {
                    b.Property<int>("DrugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DrugID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrugId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Dosage")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DrugStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DrugTitle")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly?>("Expiry")
                        .HasColumnType("date");

                    b.HasKey("DrugId")
                        .HasName("PK__Drug__908D66F624B6FE4D");

                    b.ToTable("Drug", (string)null);
                });

            modelBuilder.Entity("MediClinic.Models.DrugRequest", b =>
                {
                    b.Property<int>("DrugRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DrugRequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrugRequestId"));

                    b.Property<string>("DrugsInfoText")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("PhysicianId")
                        .HasColumnType("int")
                        .HasColumnName("PhysicianID");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("datetime");

                    b.Property<string>("RequestStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("DrugRequestId")
                        .HasName("PK__DrugRequ__AEE9D65075240E95");

                    b.HasIndex("PhysicianId");

                    b.ToTable("DrugRequest", (string)null);
                });

            modelBuilder.Entity("MediClinic.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PatientName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PatientStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Summary")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("PatientId")
                        .HasName("PK__Patient__970EC34688E81DE8");

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("MediClinic.Models.PatientMedicalProfile", b =>
                {
                    b.Property<int>("MedicalProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalProfileId"));

                    b.Property<string>("MedicalAllergies")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MedicalChronicDiseases")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MedicalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MedicalPastIllness")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("MedicalProfileId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("PatientMedicalProfile", (string)null);
                });

            modelBuilder.Entity("MediClinic.Models.Physician", b =>
                {
                    b.Property<int>("PhysicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhysicianID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhysicianId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("PhysicianName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhysicianStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Summary")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("PhysicianId")
                        .HasName("PK__Physicia__DFF5ED73B26EE8C2");

                    b.ToTable("Physician", (string)null);
                });

            modelBuilder.Entity("MediClinic.Models.PhysicianAdvice", b =>
                {
                    b.Property<int>("PhysicianAdviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhysicianAdviceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhysicianAdviceId"));

                    b.Property<string>("Advice")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID");

                    b.HasKey("PhysicianAdviceId")
                        .HasName("PK__Physicia__82C62610A3F67EE2");

                    b.HasIndex("ScheduleId");

                    b.ToTable("PhysicianAdvice", (string)null);
                });

            modelBuilder.Entity("MediClinic.Models.PhysicianPrescrip", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PrescriptionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<string>("Dosage")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("DrugId")
                        .HasColumnType("int")
                        .HasColumnName("DrugID");

                    b.Property<int?>("PhysicianAdviceId")
                        .HasColumnType("int")
                        .HasColumnName("PhysicianAdviceID");

                    b.Property<string>("Prescription")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("PrescriptionId")
                        .HasName("PK__Physicia__40130812C544648D");

                    b.HasIndex("DrugId");

                    b.HasIndex("PhysicianAdviceId");

                    b.ToTable("PhysicianPrescrip", (string)null);
                });

            modelBuilder.Entity("MediClinic.Models.PurchaseOrderHeader", b =>
                {
                    b.Property<int>("Poid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("POID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Poid"));

                    b.Property<string>("PoStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Podate")
                        .HasColumnType("datetime")
                        .HasColumnName("PODate");

                    b.Property<string>("Pono")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PONo");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    b.HasKey("Poid")
                        .HasName("PK__Purchase__5F02A2F47E24C1E8");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrderHeader", (string)null);
                });

            modelBuilder.Entity("MediClinic.Models.PurchaseProductLine", b =>
                {
                    b.Property<int>("PolineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("POLineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolineId"));

                    b.Property<int?>("DrugId")
                        .HasColumnType("int")
                        .HasColumnName("DrugID");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Poid")
                        .HasColumnType("int")
                        .HasColumnName("POID");

                    b.Property<int?>("Qty")
                        .HasColumnType("int");

                    b.Property<int?>("SlNo")
                        .HasColumnType("int");

                    b.HasKey("PolineId")
                        .HasName("PK__Purchase__07B9D3425619C648");

                    b.HasIndex("DrugId");

                    b.HasIndex("Poid");

                    b.ToTable("PurchaseProductLine", (string)null);
                });

            modelBuilder.Entity("MediClinic.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    b.Property<int?>("PhysicianId")
                        .HasColumnType("int")
                        .HasColumnName("PhysicianID");

                    b.Property<DateOnly?>("ScheduleDate")
                        .HasColumnType("date");

                    b.Property<string>("ScheduleStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ScheduleTime")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ScheduleId")
                        .HasName("PK__Schedule__9C8A5B69A01FC4E3");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PhysicianId");

                    b.ToTable("Schedule", (string)null);
                });

            modelBuilder.Entity("MediClinic.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SupplierStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("SupplierId")
                        .HasName("PK__Supplier__4BE666949E56E28B");

                    b.ToTable("Supplier", (string)null);
                });

            modelBuilder.Entity("MediClinic.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("RoleReferenceId")
                        .HasColumnType("int")
                        .HasColumnName("RoleReferenceID");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CCACC63841C7");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("MediClinic.Models.Appointment", b =>
                {
                    b.HasOne("MediClinic.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK_Appointment_Patient");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MediClinic.Models.DrugRequest", b =>
                {
                    b.HasOne("MediClinic.Models.Physician", "Physician")
                        .WithMany("DrugRequests")
                        .HasForeignKey("PhysicianId")
                        .HasConstraintName("FK_DrugRequest_Physician");

                    b.Navigation("Physician");
                });

            modelBuilder.Entity("MediClinic.Models.PatientMedicalProfile", b =>
                {
                    b.HasOne("MediClinic.Models.Patient", "Patient")
                        .WithOne("PatientMedicalProfile")
                        .HasForeignKey("MediClinic.Models.PatientMedicalProfile", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MediClinic.Models.PhysicianAdvice", b =>
                {
                    b.HasOne("MediClinic.Models.Schedule", "Schedule")
                        .WithMany("PhysicianAdvices")
                        .HasForeignKey("ScheduleId")
                        .HasConstraintName("FK_PhysicianAdvice_Schedule");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("MediClinic.Models.PhysicianPrescrip", b =>
                {
                    b.HasOne("MediClinic.Models.Drug", "Drug")
                        .WithMany("PhysicianPrescrips")
                        .HasForeignKey("DrugId")
                        .HasConstraintName("FK_Prescrip_Drug");

                    b.HasOne("MediClinic.Models.PhysicianAdvice", "PhysicianAdvice")
                        .WithMany("PhysicianPrescrips")
                        .HasForeignKey("PhysicianAdviceId")
                        .HasConstraintName("FK_Prescrip_Advice");

                    b.Navigation("Drug");

                    b.Navigation("PhysicianAdvice");
                });

            modelBuilder.Entity("MediClinic.Models.PurchaseOrderHeader", b =>
                {
                    b.HasOne("MediClinic.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrderHeaders")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK_PO_Supplier");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MediClinic.Models.PurchaseProductLine", b =>
                {
                    b.HasOne("MediClinic.Models.Drug", "Drug")
                        .WithMany("PurchaseProductLines")
                        .HasForeignKey("DrugId")
                        .HasConstraintName("FK_PurchaseLine_Drug");

                    b.HasOne("MediClinic.Models.PurchaseOrderHeader", "Po")
                        .WithMany("PurchaseProductLines")
                        .HasForeignKey("Poid")
                        .HasConstraintName("FK_PurchaseLine_PO");

                    b.Navigation("Drug");

                    b.Navigation("Po");
                });

            modelBuilder.Entity("MediClinic.Models.Schedule", b =>
                {
                    b.HasOne("MediClinic.Models.Appointment", "Appointment")
                        .WithMany("Schedules")
                        .HasForeignKey("AppointmentId")
                        .HasConstraintName("FK_Schedule_Appointment");

                    b.HasOne("MediClinic.Models.Physician", "Physician")
                        .WithMany("Schedules")
                        .HasForeignKey("PhysicianId")
                        .HasConstraintName("FK_Schedule_Physician");

                    b.Navigation("Appointment");

                    b.Navigation("Physician");
                });

            modelBuilder.Entity("MediClinic.Models.Appointment", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("MediClinic.Models.Drug", b =>
                {
                    b.Navigation("PhysicianPrescrips");

                    b.Navigation("PurchaseProductLines");
                });

            modelBuilder.Entity("MediClinic.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("PatientMedicalProfile");
                });

            modelBuilder.Entity("MediClinic.Models.Physician", b =>
                {
                    b.Navigation("DrugRequests");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("MediClinic.Models.PhysicianAdvice", b =>
                {
                    b.Navigation("PhysicianPrescrips");
                });

            modelBuilder.Entity("MediClinic.Models.PurchaseOrderHeader", b =>
                {
                    b.Navigation("PurchaseProductLines");
                });

            modelBuilder.Entity("MediClinic.Models.Schedule", b =>
                {
                    b.Navigation("PhysicianAdvices");
                });

            modelBuilder.Entity("MediClinic.Models.Supplier", b =>
                {
                    b.Navigation("PurchaseOrderHeaders");
                });
#pragma warning restore 612, 618
        }
    }
}
